# -*- coding: utf-8 -*-
"""lstm2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_io9HET_TfH8dTTEvyC7Sho_V6BdriJ
"""

import os
import re      # regex metin temizleme icin

import numpy as np     #sayisal islemler
!pip install pymupdf -q
import fitz          # pdften metin cekmek icin
import pandas as pd    #veriyi tabloya cekebilmek icin kutuphane
from sklearn.preprocessing import LabelEncoder     #veri bolme islemleri vs
from sklearn.model_selection import train_test_split

!pip install PyPDF2 -q
import PyPDF2

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Bidirectional, Dense, Dropout

from google.colab import drive                             # drivedan baglantisi kurarak veri setini yukledim

drive.mount('/content/drive')

DATASET_ROOT =  "/content/drive/MyDrive/Colab Notebooks/zor_veri_seti"


import os

print("Veri setindeki departman klasörleri:")
print(os.listdir(DATASET_ROOT))

def extract_text_from_pdf(pdf_path):                       # bu fonksiyon ile pdf icindeki metni texte cevirir.

    try:
        doc = fitz.open(pdf_path)                          # pdf dosyasini acip icindeki sayfalara erisebilmek icin
        full_text = []                                     # pdften okudugu metini bu listeye ekleyecek

        for page in doc:                                   # pdfteki tum sayfalari okuyabilmesi icin dongu
            text = page.get_text()                         # Sayfadan metni cekiyor
            full_text.append(text)                         # metni olusturdugumuz listeye ekler

        doc.close()                                        # pdf dosyasini kapatiyoruz

        return "\n".join(full_text).strip()                # okunan tum sayfalari birlestirir ve bastaki ve sondaki bosluklari siler.

    except Exception as e:                                 # hata blogu. pdf okunamazsa program cokmesin diye,
        print(f"PDF okunamadı: {pdf_path} → Hata: {e}")
        return ""

test_pdf = "/content/drive/MyDrive/veri_seti/ar_ge/arge1 (1).pdf"       # fonksiyonun dogru calisip calismadigini test ettim.
print(extract_text_from_pdf(test_pdf)[:500])

def load_dataset_from_folders(root_dir):    # bu fonksiyon her klasoru bir departman etiketi olarak alir ve tum pdfleri text label ve path seklinde tabloya ekler

    texts = []                              # burada text label ve path icin birer liste olusturduk
    labels = []
    paths = []


    for label_name in os.listdir(root_dir):                       # ana klasor altindaki departman klasorlerini tek tek dolas. yani bu 5 adet departman klasoru icin olusturdugum for dongusu.
        class_dir = os.path.join(root_dir, label_name)

        if not os.path.isdir(class_dir):                          # dosya ise atliyor cunku etiketleri alabilmemiz icin sadece klasorlere bakmasi gerekiyor su an
            continue


        for pdf_file in os.listdir(class_dir):                    # burada 5 adet departman klasorunun her birinin icindeki pdfler icin olusturdugum for dongusu. yani klasorlerin icinde dolasacak

            if not pdf_file.lower().endswith(".pdf"):             #pdf olmayan dosyalari atlar normalde hepsini pdfe cevirdim ama garanti olmasi icin
                continue

            pdf_path = os.path.join(class_dir, pdf_file)          # o an for dongusunun ustunde oldugu dosya bilgilerini alir bu dosya ile islem yapacagiz


            text = extract_text_from_pdf(pdf_path)                # pdfi metne cevirebilmek icin yazdigimiz fonksiyonu kullandik

            if len(text.strip()) == 0:                            # pdf bos ise atla
                continue

            texts.append(text)                                    # burada okudugu pdfin test label ve path bilgilerini en basta olustuirdugumuz listeye ekliyor.
            labels.append(label_name)
            paths.append(pdf_path)


    df = pd.DataFrame({                                         # tabloyu olustur
        "text": texts,
        "label": labels,
        "path": paths
    })

    return df                                                   # tabloyu dondur

df = load_dataset_from_folders(DATASET_ROOT)        # tabloyu olusturabiliyor mu diye test kodu
df.head()

X = df["text"]      # Belgelerin metinleri
y = df["label"]     # Hangi departman (IK, Finans, Hukuk, MH, ArGe)

# veriyi eğitim ve test olarak böleceğiz
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,       # verinin %20'si test, %80'i eğitim
    random_state=42,     # sonuçları tekrar üretilebilir yapmak için
    stratify=y           # her departmandan orantılı örnek gelsin
)

print("Toplam örnek sayısı:", len(df))
print("Eğitim seti sayısı:", len(X_train))
print("Test seti sayısı:", len(X_test))

print("\nEğitim seti sınıf dağılımı:")
print(y_train.value_counts())

print("\nTest seti sınıf dağılımı:")
print(y_test.value_counts())

def clean_text(text):                                      #GURULTUSUZ VERI SETI
    text = text.lower()        #hepsini kucuk harf yapar
    text = text.replace("\n", " ")    #satir sonuna bosluk yapiyor metin tek bir satir gibi okunuyor
    text = re.sub(r"[^0-9a-zçğıöşüı\s]", " ", text) #icindeki karakterler haricini temizliyor
    text = re.sub(r"\s+", " ", text).strip() #noktalama isaretlerini bosluk yapiyor ve bastaki ve sondaki bosluklari siliyor
    return text

  #yani aslinda burda gereksiz isaretleri vb temizleyerek modelin asil bilgiye odaklanmasini sagladik

# eğitim ve test verisine uygula
X_train_clean = X_train.apply(clean_text)
X_test_clean  = X_test.apply(clean_text)

max_words = 20000
max_seq_len = 500

tokenizer = Tokenizer(num_words=max_words, oov_token="<UNK>")  #en cok kullanilan 20000 sozcugu sozluge al bir kelime sozlukte yoksa unk id si ver
tokenizer.fit_on_texts(X_train_clean)  #tum kelimelere bir id atiyor

train_seq = tokenizer.texts_to_sequences(X_train_clean)   # id atamistik mesela zeynep sakaoglu = [28 , 931] olarak idlerini diziye atadi
test_seq  = tokenizer.texts_to_sequences(X_test_clean)

X_train_pad = pad_sequences(train_seq, maxlen=max_seq_len, padding="post")  #her belgenin uzunlugunu 500e sabitliyot fazlaysa 500de kesiyor azsa sonunu 0 ile dolduruyor
X_test_pad  = pad_sequences(test_seq,  maxlen=max_seq_len, padding="post")


#bunun sebebi lstmin sabit uzunlukta input degeri beklemesi ve metni sayiya cevirmezsek lstm kullnamiyoruz

le = LabelEncoder()   #departman isimlerini de integer degerlere ceviriyoruz yani dep isimlerine de id atiyoruz
le.fit(y_train)

y_train_enc = to_categorical(le.transform(y_train))   #idleri vektor haline getiriyor
y_test_enc  = to_categorical(le.transform(y_test))



#idleri vektor haline getirmesinin sebebi cikis katmaninda softmax kullaniyor olmak cunku bu vektor uretiyor

embedding_dim = 128
num_classes = len(le.classes_)

model = Sequential([
    Embedding(input_dim=max_words, output_dim=embedding_dim, input_length=max_seq_len, input_shape=(max_seq_len,)
    #girdi=500, cikti her kelime 128 boyutlu vektor,
),
    Bidirectional(LSTM(64)), # 64 birimlik lstmi hem geri hem ileri yonde calistirir bizim cikti 128di 64 ileri 64 geri
    #belgenin basi ve sonu arasindaki iliskileri yakalar
    Dropout(0.3),
    Dense(64, activation="relu"),  #lstmin 128 boyutlu ciktisini 64 boyutlu vektore sikistirir
    Dropout(0.3),
    Dense(num_classes, activation="softmax")  # 5 sinif icin olasiliklari uretecek
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

history = model.fit(         # model egitme adimi
    X_train_pad, y_train_enc,
    validation_split=0.2,      # egitim verisinin %20sini validation icin ayirdik
    epochs=10,
    batch_size=32
)

import matplotlib.pyplot as plt

# Accuracy grafiği
plt.figure(figsize=(6,4))
plt.plot(history.history["accuracy"], label="Eğitim doğruluğu")
plt.plot(history.history["val_accuracy"], label="Doğrulama doğruluğu")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Eğitim / Doğrulama Doğruluğu")
plt.legend()
plt.grid(True)
plt.show()

# Loss grafiği
plt.figure(figsize=(6,4))
plt.plot(history.history["loss"], label="Eğitim kaybı")
plt.plot(history.history["val_loss"], label="Doğrulama kaybı")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Eğitim / Doğrulama Kaybı")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Test seti için tahminler
y_pred_proba = model.predict(X_test_pad)
y_pred_int   = np.argmax(y_pred_proba, axis=1)

# Gerçek etiketleri integer forma çevir
y_true_int = le.transform(y_test)

cm = confusion_matrix(y_true_int, y_pred_int)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)

plt.figure(figsize=(6,5))
disp.plot(cmap="Blues", values_format="d")
plt.title("Confusion Matrix - Test Seti")
plt.xticks(rotation=45)
plt.show()

from sklearn.metrics import classification_report, precision_score, recall_score, f1_score

print("=== Classification Report ===")
print(classification_report(y_true_int, y_pred_int, target_names=le.classes_))


precision_macro = precision_score(y_true_int, y_pred_int, average="macro")
recall_macro    = recall_score(y_true_int, y_pred_int, average="macro")
f1_macro        = f1_score(y_true_int, y_pred_int, average="macro")

precision_weighted = precision_score(y_true_int, y_pred_int, average="weighted")
recall_weighted    = recall_score(y_true_int, y_pred_int, average="weighted")
f1_weighted        = f1_score(y_true_int, y_pred_int, average="weighted")

print("\nMacro avg  ->  Precision: {:.3f}, Recall: {:.3f}, F1: {:.3f}".format(
    precision_macro, recall_macro, f1_macro))

print("Weighted avg -> Precision: {:.3f}, Recall: {:.3f}, F1: {:.3f}".format(
    precision_weighted, recall_weighted, f1_weighted))

loss, acc = model.evaluate(X_test_pad, y_test_enc, verbose=0)
print(f"Test accuracy: {acc:.4f}")

def predict_text(text):
    text = clean_text(text)
    seq = tokenizer.texts_to_sequences([text])
    pad = pad_sequences(seq, maxlen=max_seq_len, padding="post")

    proba = model.predict(pad)[0]  #modelden tahmin aliyor
    idx = np.argmax(proba)        # en yuksek olasilikli sinifi model tahmini olarak aliyor
    label = le.inverse_transform([idx])[0] #idye cevirdigimiz departman isimlerini tekrar stringe ceviriyor

    return label, proba

import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

def predict_pdf_department_proba_lstm(model, tokenizer, label_encoder, pdf_path, max_seq_len):



    text = extract_text_from_pdf(pdf_path)  #pdften metni okur

    if not text.strip():
        print(f"Uyarı: PDF'ten metin okunamadı -> {pdf_path}")
        return None

    #  Metni temizle (küçük harf, noktalama sadeleştirme vs.)
    text_clean = clean_text(text)

    if not text_clean.strip():
        print(f"Uyarı: Temizleme sonrası metin boş -> {pdf_path}")
        return None

    #  Tokenizer + padding
    seq = tokenizer.texts_to_sequences([text_clean])
    padded = pad_sequences(seq, maxlen=max_seq_len, padding="post", truncating="post")

    #  Modelden olasılıkları al
    proba = model.predict(padded)[0]   # shape: (sınıf_sayısı,)

    #  Sınıf isimlerini al (LabelEncoder üzerinden)
    class_indices = np.arange(len(proba))
    class_names = label_encoder.inverse_transform(class_indices)  # örn: ['ar_ge', 'finans', ...]

    #  Sınıf-olasılık sözlüğü
    prob_dict = {cls: float(p) for cls, p in zip(class_names, proba)}

    # Büyükten küçüğe sırala
    prob_dict_sorted = dict(sorted(prob_dict.items(), key=lambda x: x[1], reverse=True))

    return prob_dict_sorted

example_pdf_path = "/content/drive/MyDrive/Yesil Sertifika Sistemi (YeS-TR).pdf"

probs = predict_pdf_department_proba_lstm(
    model,
    tokenizer,
    le,             # LabelEncodere le demistim
    example_pdf_path,
    max_seq_len
)

if probs is not None:
    print("\nBu belge için departman olasılıkları:")
    for dept, p in probs.items():
        print(f"{dept:20s} -> %{p*100:.2f}")
else:
    print("Tahmin üretilemedi (muhtemelen PDF okunamadı).")

import random
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import os


SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input
from tensorflow.keras.callbacks import EarlyStopping



X_temp, X_final_test, y_temp, y_final_test = train_test_split(    #burda %10unu ayirdim hic gormedigi veri setinde test edebilmek icin
    X, y, test_size=0.10, random_state=42, stratify=y
)

X_train_clean, X_test_clean, y_train, y_test = train_test_split(
    X_temp, y_temp, test_size=0.20, random_state=42, stratify=y_temp
)

print(f"Train: {len(X_train_clean)} | Test: {len(X_test_clean)} | Final: {len(X_final_test)}")


le = LabelEncoder()
y_train_enc = to_categorical(le.fit_transform(y_train))
y_test_enc  = to_categorical(le.transform(y_test))
y_final_enc = to_categorical(le.transform(y_final_test))

num_classes = y_train_enc.shape[1]


turkish_chars = "abcçdefgğhıijklmnoöprsştuüvyz"             #diger gurultu kodunu birebir aldim

def add_noise_to_text(text, drop_prob=0.05, swap_prob=0.03, char_noise_prob=0.02):
    words = text.split()
    if len(words) < 2:
        return text

    noisy_words = []
    for w in words:
        if random.random() < drop_prob:
            continue
        if random.random() < char_noise_prob and len(w) > 3:
            idx = random.randint(0, len(w)-1)
            w = w[:idx] + random.choice(turkish_chars) + w[idx+1:]
        noisy_words.append(w)

    if len(noisy_words) == 0:
        noisy_words = words

    i = 0
    while i < len(noisy_words)-1:
        if random.random() < swap_prob:
            noisy_words[i], noisy_words[i+1] = noisy_words[i+1], noisy_words[i]
            i += 2
        else:
            i += 1

    return " ".join(noisy_words)

def shuffle_paragraphs(text):
    parts = text.split("\n\n")
    random.shuffle(parts)
    return "\n\n".join(parts)

X_train_noisy = X_train_clean.apply(add_noise_to_text).apply(shuffle_paragraphs)


tokenizer= Tokenizer(num_words=max_words, oov_token="<UNK>")
tokenizer.fit_on_texts(X_train_noisy)

X_train_pad = pad_sequences(
    tokenizer.texts_to_sequences(X_train_noisy),
    maxlen=max_seq_len, padding="post"
)

X_test_pad = pad_sequences(
    tokenizer.texts_to_sequences(X_test_clean),
    maxlen=max_seq_len, padding="post"
)

X_final_pad = pad_sequences(
    tokenizer.texts_to_sequences(X_final_test),
    maxlen=max_seq_len, padding="post"
)


model_noisy = Sequential([
    Input(shape=(max_seq_len,)),
    Embedding(input_dim=max_words, output_dim=128),
    Bidirectional(LSTM(32)),   # recurrent_dropout YOK
    Dropout(0.3),
    Dense(32, activation="relu"),
    Dropout(0.3),
    Dense(num_classes, activation="softmax")
])

model_noisy.compile(
    optimizer="adam",
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.05),
    metrics=["accuracy"]
)

model_noisy.summary()



early_stop = EarlyStopping(
    monitor="val_loss",
    patience=4,
    restore_best_weights=True
)

history = model_noisy.fit(
    X_train_pad, y_train_enc,
    validation_data=(X_test_pad, y_test_enc),
    epochs=20,
    batch_size=32,
    #callbacks=[early_stop],
    verbose=1
)


plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(history.history["accuracy"], label="Train")
plt.plot(history.history["val_accuracy"], label="Val")
plt.legend(); plt.title("Accuracy")

plt.subplot(1,2,2)
plt.plot(history.history["loss"], label="Train")
plt.plot(history.history["val_loss"], label="Val")
plt.legend(); plt.title("Loss")

plt.show()



y_test_pred = np.argmax(model_noisy.predict(X_test_pad), axis=1)
cm_test = confusion_matrix(np.argmax(y_test_enc, axis=1), y_test_pred)

plt.figure(figsize=(7,6))
sns.heatmap(cm_test, annot=True, fmt="d",
            xticklabels=le.classes_,
            yticklabels=le.classes_, cmap="Blues")
plt.title("Confusion Matrix - TEST")
plt.show()

y_final_pred = np.argmax(model_noisy.predict(X_final_pad), axis=1)
cm_final = confusion_matrix(np.argmax(y_final_enc, axis=1), y_final_pred)

plt.figure(figsize=(7,6))
sns.heatmap(cm_final, annot=True, fmt="d",
            xticklabels=le.classes_,
            yticklabels=le.classes_, cmap="Greens")
plt.title("Confusion Matrix - FINAL")
plt.show()

pdf_path = "/content/drive/MyDrive/Kirikkale Universitesi Uzaktan Egitim Uygulama ve Arastirma Merkezi Mudurlugune Gorevlendirme.pdf"
predict_pdf_department_proba_lstm(model_noisy, tokenizer , le, pdf_path , max_seq_len)

model_noisy.save('belge_modeli.h5')